[project]
name = "python-polylith"
version = "1.0.0"
description = "A Python Polylith repo adding tooling support for the Polylith Architecture"
authors = [{ name = "David Vujic" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8.1,<4"
dependencies = [
    "poetry",
    "tomlkit>=0,<1",
    "rich>=13,<16; python_version >= '3.9'",
    "rich>=13,<15; python_version < '3.9'",
    "cleo~=2.1.0",
    "hatchling~=1.21.0",
    "typer>=0,<1",
    "pyyaml",
    "typing_extensions>=4.14; python_version >= '3.9'",
    "typing_extensions<4.14; python_version < '3.9'"
]

[project.urls]
Homepage = "https://github.com/davidvujic/python-polylith"
Documentation = "https://davidvujic.github.io/python-polylith-docs/"

[dependency-groups]
dev = [
  "isort~=5.10.1",
  "mypy~=1.14.0",
  "flake8~=7.0.0",
  "pytest~=8.3.5",
  "types-pyyaml~=6.0.12.20241230"
]

[tool.polylith.bricks]
"bases/polylith/cli" = "polylith/cli"
"bases/polylith/pdm_project_hooks" = "polylith/pdm_project_hooks"
"bases/polylith/hatch_hooks" = "polylith/hatch_hooks"
"bases/polylith/pdm_workspace_hooks" = "polylith/pdm_workspace_hooks"
"bases/polylith/poetry_plugin" = "polylith/poetry_plugin"
"components/polylith/hatch" = "polylith/hatch"
"components/polylith/poetry" = "polylith/poetry"
"components/polylith/parsing" = "polylith/parsing"
"components/polylith/readme" = "polylith/readme"
"components/polylith/deps" = "polylith/deps"
"components/polylith/yaml" = "polylith/yaml"
"components/polylith/building" = "polylith/building"
"components/polylith/check" = "polylith/check"
"components/polylith/workspace" = "polylith/workspace"
"components/polylith/reporting" = "polylith/reporting"
"components/polylith/dirs" = "polylith/dirs"
"components/polylith/configuration" = "polylith/configuration"
"components/polylith/diff" = "polylith/diff"
"components/polylith/distributions" = "polylith/distributions"
"components/polylith/bricks" = "polylith/bricks"
"components/polylith/pdm" = "polylith/pdm"
"components/polylith/output" = "polylith/output"
"components/polylith/environment" = "polylith/environment"
"components/polylith/development" = "polylith/development"
"components/polylith/libs" = "polylith/libs"
"components/polylith/project" = "polylith/project"
"components/polylith/commands" = "polylith/commands"
"components/polylith/sync" = "polylith/sync"
"components/polylith/toml" = "polylith/toml"
"components/polylith/files" = "polylith/files"
"components/polylith/imports" = "polylith/imports"
"components/polylith/alias" = "polylith/alias"
"components/polylith/interface" = "polylith/interface"
"components/polylith/interactive" = "polylith/interactive"
"components/polylith/repo" = "polylith/repo"
"components/polylith/test" = "polylith/test"
"components/polylith/info" = "polylith/info"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-sv"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
