[tool.polylith]
namespace = "polylith"

[tool.polylith.structure]
bricks = "{brick}/{namespace}/{package}"
tests = "test/{brick}/{namespace}/{package}"

[tool.polylith.test]
enabled = true
template = """\
from {namespace}.{package} import {modulename}


def test_sample():
    assert {modulename} is not None
"""