name: Pull Request

on:
  pull_request:
    branches:
      - "*"

    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Test Suite"
        uses: ./.github/actions/test_suite

  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Lint Suite"
        uses: ./.github/actions/linting
